### ISSUE TITLE
Stuck on YAAP boot animation.

### ISSUE THREAD

**Issue by StupidRepo** [captaincookie200/treble_yaap#7]
I flashed the latest (at time of post) GSI (it was varient bgN) and I'm stuck on the YAAP animation. It's been 7 minutes, and nothing has happened. How do I obtain logs from this stage?

My device is a Redmi Note 10 5G.

**Comment by StupidRepo** [comment]
If I hold down the Volume Down button, it starts vibrating every 2 seconds. I still don't see anything so I'm scared that it may be calling emergency services (so I just keep restarting the phone)

**Comment by realahnet** [comment]
> If I hold down the Volume Down button, it starts vibrating every 2 seconds. I still don't see anything so I'm scared that it may be calling emergency services (so I just keep restarting the phone)

There was a new patch for Xiaomi FOD to fix it for some xiaomi devices. But looks like phh forgot to add sepolicy rules for it preventing it from booting. Expect a new build today that would fix this issue. Sorry for the inconvenience. You can dirty flash the old build for now

**Comment by realahnet** [comment]
> > If I hold down the Volume Down button, it starts vibrating every 2 seconds. I still don't see anything so I'm scared that it may be calling emergency services (so I just keep restarting the phone)
> 
> There was a new patch for Xiaomi FOD to fix it for some xiaomi devices. But looks like phh forgot to add sepolicy rules for it preventing it from booting. Expect a new build today that would fix this issue. Sorry for the inconvenience. You can dirty flash the old build for now

ONe more thing. delete the gsi at /data/adb/gsi

i am sorry im not aware of the exact directory of the gsi but without deleting it. rom will continue booting from the broken ota

**Comment by StupidRepo** [comment]
Thank you! I'll be sure to take a look ASAP.

**Comment by StupidRepo** [comment]
> > > If I hold down the Volume Down button, it starts vibrating every 2 seconds. I still don't see anything so I'm scared that it may be calling emergency services (so I just keep restarting the phone)
> > 
> > 
> > There was a new patch for Xiaomi FOD to fix it for some xiaomi devices. But looks like phh forgot to add sepolicy rules for it preventing it from booting. Expect a new build today that would fix this issue. Sorry for the inconvenience. You can dirty flash the old build for now
> 
> ONe more thing. delete the gsi at /data/adb/gsi
> 
> i am sorry im not aware of the exact directory of the gsi but without deleting it. rom will continue booting from the broken ota

Ok so it's still stuck on the YAAP animation, however pressing&holding the volume down button doesn't make it vibrate. Strange...

**Comment by realahnet** [comment]
> > > > If I hold down the Volume Down button, it starts vibrating every 2 seconds. I still don't see anything so I'm scared that it may be calling emergency services (so I just keep restarting the phone)
> > > 
> > > 
> > > There was a new patch for Xiaomi FOD to fix it for some xiaomi devices. But looks like phh forgot to add sepolicy rules for it preventing it from booting. Expect a new build today that would fix this issue. Sorry for the inconvenience. You can dirty flash the old build for now
> > 
> > 
> > ONe more thing. delete the gsi at /data/adb/gsi
> > i am sorry im not aware of the exact directory of the gsi but without deleting it. rom will continue booting from the broken ota
> 
> Ok so it's still stuck on the YAAP animation, however pressing&holding the volume down button doesn't make it vibrate. Strange...

Try the new build 20230902 and delete the gsi file in data like i told you.

if that doesnt boot too that means i'd have to entirely just drop the xiaomi patch

**Comment by realahnet** [comment]
> > > > > If I hold down the Volume Down button, it starts vibrating every 2 seconds. I still don't see anything so I'm scared that it may be calling emergency services (so I just keep restarting the phone)
> > > > 
> > > > 
> > > > There was a new patch for Xiaomi FOD to fix it for some xiaomi devices. But looks like phh forgot to add sepolicy rules for it preventing it from booting. Expect a new build today that would fix this issue. Sorry for the inconvenience. You can dirty flash the old build for now
> > > 
> > > 
> > > ONe more thing. delete the gsi at /data/adb/gsi
> > > i am sorry im not aware of the exact directory of the gsi but without deleting it. rom will continue booting from the broken ota
> > 
> > 
> > Ok so it's still stuck on the YAAP animation, however pressing&holding the volume down button doesn't make it vibrate. Strange...
> 
> Try the new build 20230902 and delete the gsi file in data like i told you.
> 
> if that doesnt boot too that means i'd have to entirely just drop the xiaomi patch

make sure you delete the file in /data

**Comment by StupidRepo** [comment]
Ohhh hold on... How can I delete the file(s) if I can't use `adb` (since it's stuck on the boot screen)? Do I just use `fastboot -w`?

**Comment by realahnet** [comment]
> Ohhh hold on... How can I delete the file(s) if I can't use `adb` (since it's stuck on the boot screen)? Do I just use `fastboot -w`?

um.. do you not have a custom recovery. in which case if u do not have important data then just wipe. Also please wait for 20230902-hotfix

apparently the new sepolicy rules are also broken

**Comment by StupidRepo** [comment]
No custom recovery :(
Guess I'll wait for `-hotfix`.

**Comment by realahnet** [comment]
> No custom recovery :( Guess I'll wait for `-hotfix`.

thats kind of an issue. Build uploading right now. make sure to wipe data like u are clean flashing otherwise it will continue to bootloop. i sincerely apologize for such a inconvenience i had no idea this would happen and i would adapt a more testing strategy before publishing future builds. i hope i didnt cause too much of an issue. I am really sorry.

**Comment by realahnet** [comment]
> No custom recovery :( Guess I'll wait for `-hotfix`.

please try the build 20230903

**Comment by StupidRepo** [comment]
Alright will do.
> i hope i didnt cause too much of an issue. I am really sorry.

Hey, it's OK. Thank you for being really helpful and responding ASAP :)

**Comment by StupidRepo** [comment]
Ahhh it works now! Thank you so much! Before I close this issue, what is FOD?
